### ISSUE TITLE
[question]: would k6chaijs support to display report summary like k6 group do now?

### ISSUE THREAD

**Issue by BrendaAspen** [grafana/k6-jslib-k6chaijs#7]
First, I want to thank for the sharing, it is nice.
When I learn it by the sample. It works well.
But, I have a small question. I want to know would we use **describe** to show the result in report summary later?
Now, it cannot, we need to user k6 group,  please see below pictures.
**Without k6 group:**
![image](https://user-images.githubusercontent.com/80807221/198915237-843ad113-a08e-40d0-9303-49d1025b59c7.png)

**Result with k6 group and describe:**
![image](https://user-images.githubusercontent.com/80807221/198914793-3aee8941-9a9e-4d4e-9ea1-e80e11e9302c.png)

**Comment by EdvinasDaugirdas** [comment]
Hey @BrendaAspen , thanks for checking out the library!

As for your posted issue - `describe` is just a wrapper around `group`, so whatever you can do with a `group` you should be able to do with a `describe` block.

The issue that you're facing is connected with your threshold definition. 

In **k6 group** example your defining a threshold on a root group, which has a correct threshold definition, so it works as expected:

```javascript
export let options = {
  thresholds: {
    'group_duration{group:::From k6 group: should fetch a list of public crocodiles}': ['p(95)<5000']
  }
}
```

In **Without k6 group** example the threshold you're trying to reach is in a subgroup, hence you're not seeing the expected results. The correct syntax would be: 

```javascript
export let options = {
  thresholds: {
    'group_duration{group:::crocodiles API::should fetch a list of public crocodiles}': ['p(95)<5000']
  }
}
```

So whenever you want to reach a subgroup (meaning a group within a group) use the following syntax:

```javascript
export let options = {
  thresholds: {
    'group_duration{group:::root_group::sub_group}': ['p(95)<5000']
  }
}
```
